version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: skillmatch-mongodb
    restart: always
    command: mongod --port 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: mario
      MONGO_INITDB_ROOT_PASSWORD: arrigoni
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db

  skillmatch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillmatch-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mario:arrigoni@mongodb:27018/skillmatch?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./src/main/resources/static:/app/static

volumes:
  mongodb_data: